version: "3"

services:
  app:
    image: docker-nextjs-dev
    env_file: ./.env
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./app:/app/app
      - ./components:/app/components
      - ./constants:/app/constants
      - ./public:/app/public
      - ./types:/app/types
      - ./utils:/app/utils
